### ISSUE TITLE
Play date with Klipper

### ISSUE THREAD

**Issue by jault83** [dzomaya/NUTandRpi#13]
Good day! I have stumbled across this wonderful Git, have everything installed just so. However when trying to navigate through my browser, it's pulling up my Klipper interface rather than NUT. Please help! I'm very novice at this, I'm sure there is a work around but I should would appreciate some help. Thank you!

**Comment by jault83** [comment]
Thank you for the reply! Klipper is using port 80, and Moonraker is using 7125. I do not see that configuration file you mentioned, I searched my Pi for it and cannot find it. Looking at Apache's documentation, I should also have the file httpd.conf but I cannot find that file either. I'm going to attempt to reinstall Apache and go from there.

**Comment by dzomaya** [comment]
@jault83 
I'll close this one for now, but feel free to comment if you have any issues.
