### ISSUE TITLE
Error: no UPS definitions found in ups.conf during install

### ISSUE THREAD

**Issue by biiiink** [dzomaya/NUTandRpi#14]
I noticed an error during the install

Would this mean that my UPS [CyberPower PR1500LCDRT2U from 2014](https://www.cyberpowersystems.com/product/ups/smart-app-sinewave/pr1500lcdrt2u/) is not compatible?
I have had it working with NUT previously.

```Network UPS Tools - UPS driver controller 2.8.1
Error: no UPS definitions found in ups.conf
Network UPS Tools upsd 2.8.1
fopen /run/nut/upsd.pid: No such file or directory
Could not find PID file '/run/nut/upsd.pid' to see if previous upsd instance is already running!
listening on ::1 port 3493
listening on 127.0.0.1 port 3493
Warning: no UPS definitions in ups.conf
Fatal error: at least one UPS must be defined in ups.conf
Error: Connection failure: Connection refused
Your MPM seems to be threaded. Selecting cgid instead of cgi.
Enabling module cgid.
To activate the new configuration, you need to run:
  systemctl restart apache2```

**Comment by dzomaya** [comment]
Hi @biiiink ! 
Thanks for using the project. 
I don't see `PR1500LCDRT2U` on the [NUT hardware compatibility list (HCL)](https://networkupstools.org/stable-hcl.html). I do see a "[PR1500RT2U](https://networkupstools.org/ddl/Cyber_Power_Systems/PR1500RT2U.html)", but I am not sure how similar those two are. Edit: if you had it working with NUT previously, I would expect it to work now. 

Can you check:

1. the output of `lsusb` 
2. The output of `nut-scanner -UNq`? 
3. The output of `cat /etc/nut/ups.conf`

Can you also confirm what version of NUT and operating system this worked on before? Is it the same as what you are using now?

**Comment by dzomaya** [comment]
Hi @biiiink 
Did you get this working?

**Comment by biiiink** [comment]
I was not able to get this working.  But I was able to get it working through Home Assistant, so that is what I will continue using for now.

**Comment by dzomaya** [comment]
Thanks! I'll close this one for now.
